name: "\U0001F41E Bug report"
description: Report an issue
labels: [pending triage]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: plugins
    attributes:
      label: Related plugins
      description: Select the plugin which is related
      options:
        - label: |
            [plugin-react](https://github.com/dazum-dev/toolbox/tree/main/packages/plugin-react)
        - label: |
            [dev](https://github.com/dazum-dev/toolbox/tree/main/packages/dev)
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. E.g. if it happens only when running the dev or build script make sure it's clear which one to use.
      placeholder: Run `npm install` followed by `npm run dev`
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.

        1. Provide the error log here in the format below.

        ````
        <details>
        <summary>Click to expand!</summary>

        ```shell
        // paste the log text here
        ```
        </details>
        ````
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/dazum-dev/toolbox/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/dazum-dev/toolbox/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://dazum.app).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/dazum-dev/toolbox/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
